backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "hours"
    label: "Hours"
    folder: "content/hours"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Sunday", name: "sunday", widget: "string" }
      - { label: "Monday", name: "monday", widget: "string" }
      - { label: "Tuesday", name: "tuesday", widget: "string" }
      - { label: "Wednesday", name: "wednesday", widget: "string" }
      - { label: "Thursday", name: "thursday", widget: "string" }
      - { label: "Friday", name: "friday", widget: "string" }
      - { label: "Saturday", name: "saturday", widget: "string" }