backend:
  name: git-gateway
  repo: JoshDrentlaw/worm-website
  branch: master

media_folder: static/assets

collections:
  - name: hours
    label: Hours
    folder: content/hours
    create: true
    fields:
      - { label: Title, name: title, widget: string, default: "Hours" }
      - { label: Sunday, name: sunday, widget: string, default: "Closed" }
      - { label: Monday, name: monday, widget: string, default: "9:00am-12:00pm" }
      - { label: Tuesday, name: tuesday, widget: string, default: "9:00am-12:00pm" }
      - { label: Wednesday, name: wednesday, widget: string, default: "9:00am-12:00pm" }
      - { label: Thursday, name: thursday, widget: string, default: "9:00am-12:00pm" }
      - { label: Friday, name: friday, widget: string, default: "9:00am-12:00pm" }
      - { label: Saturday, name: saturday, widget: string, default: "Closed" }
  
  - name: faq
    label: FAQ
    folder: content/faq
    create: true
    fields:
      - { label: Title, name: title, widget: string, default: "FAQ" }
      - { label: Body, name: body, widget: markdown }