backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
collections:
  - name: "hours"
    label: "Hours"
    folder: "admin/hours"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Sunday Hours", name: "sunday hours", widget: "string"}
      - {label: "Monday Hours", name: "monday hours", widget: "string"}
      - {label: "Tuesday Hours", name: "tuesday hours", widget: "string"}
      - {label: "Wednesday Hours", name: "wednesday hours", widget: "string"}
      - {label: "Thursday Hours", name: "thursday hours", widget: "string"}
      - {label: "Friday Hours", name: "friday hours", widget: "string"}
      - {label: "Saturday Hours", name: "saturday hours", widget: "string"}
media_folder: "admin/uploads"