backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
collections:
  - name: "hours"
    label: "Hours"
    folder: "admin/hours"
    create: true
    identifier_field: "new hours"
    extension: json
    format: json
    slug: "{{slug}}"
    fields:
      - {label: "New Hours", name: "new hours", widget: "string", default: "New Hours"}
      - {label: "Sunday", name: "sunday", widget: "string"}
      - {label: "Monday", name: "monday", widget: "string"}
      - {label: "Tuesday", name: "tuesday", widget: "string"}
      - {label: "Wednesday", name: "wednesday", widget: "string"}
      - {label: "Thursday", name: "thursday", widget: "string"}
      - {label: "Friday", name: "friday", widget: "string"}
      - {label: "Saturday", name: "saturday", widget: "string"}
media_folder: "admin/uploads"